config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  get "/tasks/new", to: "tasks#new", as: :create_task
  # See all tasks
  get "/tasks", to: "tasks#index", as: :tasks
  # See details about one post
  get "/tasks/:id", to: "tasks#show", as: :task
  # Create a post
  post "/tasks", to: "tasks#create"
  # Update a post
  get "/tasks/:id/edit", to: "tasks#edit", as: :update_task
  patch "/tasks/:id", to: "tasks#update"
  # Destroy a post
  delete "/tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@tasks)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
<% @tasks.each do |t| %>

  <li><%= link_to t.title, task_path(t) %></li>
<% end %>
</ul>

<small><%= link_to "Add task", create_task_path %></small>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= "#{@task.title}" %></h1>

<small><%= link_to "Delete #{@task.title}", delete_task_path(@task), method: :delete, data: {confirm: "Are you sure?"} %></small>

<small><%= link_to "Edit #{@task.title}", update_task_path(@task) %></small>

<ul>
    <li><%= @task.details%></li>
    <li><%= @task.completed%></li>
</ul>



<small><%= link_to "Back to tasks list", tasks_path %></small>